title: Projekt 1 KK
baseURL: https://determined-gates-94ba5d.netlify.com
languageCode: cs-cz
publishDir: public

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Description of my new site.
  authors: Authors

